import datetime
import os

from flask import Blueprint, jsonify, send_from_directory

download_file_bp = Blueprint("download_file_bp", __name__)


@download_file_bp.route('/download', methods=['GET'])
def download_file():
    """
    API endpoint to download the output Excel file.

    This endpoint allows users to download the Excel file containing the sales forecast
    generated by the system. The file is located in the 'generated_reports' directory
    and its name includes the current date. If the file is found, it is served for download.
    If the file is not found, a 404 error response is returned.

    Returns:
        Response: The Excel file for download if found.
            - If the file is found and served successfully, returns the Excel file.
        Error Response: JSON response indicating the error message if the file is not found or if
                        an error occurs during the download process.
            - If the file is not found, returns a 404 error response with a message "File not found".
            - If an error occurs during the download process, returns a 500 error response with a
              message "Some error occurred".
    """

    try:
        postfix = datetime.datetime.now().isoformat().replace("-", "_").split("T")[0]
        out_dir = os.path.join("resources", "generated_reports")
        file_name = f"SalesForecast{postfix}.xlsx"
        file = os.path.join(out_dir, file_name)
        if not os.path.exists(file):
            print("File nhi mili!!!", file)
            return {"message": "File not found"}, 404
        return send_from_directory(out_dir, file_name)
    except Exception as err:
        print(f"{type(err).__name__}: {str(err)}")
        return {"message": "Some error occurred"}, 500
